apiVersion: sources.knative.dev/v1alpha2
kind: PingSource
metadata:
  name: eventinghello-ping-source
spec:
  jsonData: '{"message": "Thanks for doing Knative Tutorial"}'
  schedule: '*/2 * * * *'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: eventinghello
